### ISSUE TITLE
Sensor reverts to CFG mode on power cycle

### ISSUE THREAD

**Issue by cmydlarz** [floodnet-nyc/flood-sensor#32]
It seems that on a hard power cycle a sensor reverts to the `CFG` state. We should store the last state locally and have it resume where it left off as gateway rainfall sensors will likely power cycle and cant be left in the `CFG` state.

**Comment by Praneethsvch** [comment]
fixed a1d7071789cf7c05d9f0e98657d7d2f1241fa464
