### ISSUE TITLE
RCA - 4th Ave & Garfield

### ISSUE THREAD

**Issue by Praneethsvch** [floodnet-nyc/flood-sensor#59]
### Issue/Bug/Suggestion 
  - Sensor stopped working on 5/6/2023, 12:12
 
  ### Sensor version and firmware version 
  - v2 , firmware version: [4.3.1](https://github.com/floodnet-nyc/flood-sensor/tree/4.3.1)

  ### Metadata
  1. `deployment_id` - daily_gentle_beetle
  2. `dev_id` - fs-00002
  3. deployed by - FloodNet

  ### Fixes/Action
  - RCA needed

**Comment by ak6492** [comment]
linked to more recently open 4th Ave and Garfield issue
