### ISSUE TITLE
Buswick Troubleshooting

### ISSUE THREAD

**Issue by mprafull1** [floodnet-nyc/flood-sensor#62]
2 sensors were deployed on 06/02/2023. 
Dev_ids - 
fs-00056 - Knibocker ave/Hart st
fs-00090 - Morgan ave/ Johnson ave

fs-00090 :
 Issue-
Missing lots of data packets but getting uplinks and downlinks. 

Analysis-
Low network coverage
![Screenshot 2023-06-12 180403](https://github.com/floodnet-nyc/flood-sensor/assets/128631973/4f455d30-e97f-42f4-8e52-c7f16b878e9c)
Battery is okay.
loss packet percentage - 94.4%
Surrounded by warehouses and its 0.904 mile from the  gateway that is placed at 303 Vernon.

fs-00056:
Issue- Missing comparatively less packets but not getting downlinks.

Analysis-
Network coverage is comparatively better but still low
![Screenshot 2023-06-12 180427](https://github.com/floodnet-nyc/flood-sensor/assets/128631973/1ed7a62e-679f-432b-9aa8-e0420e94b1d8)
loss packet percentage - 56%
Surrounded by buildings and its 0.975 mile from the  gateway that is placed at 303 Vernon.

**Comment by ak6492** [comment]
New Gateway in Bushwick and use of the remote gateway has helped bring these two sensors up
