### ISSUE TITLE
RCA - Russell St 1

### ISSUE THREAD

**Issue by ak6492** [floodnet-nyc/flood-sensor#67]
Sensor Deployed:

March 5, 2021 by FloodNet
Sensor Version:

v2.0.
Firmware Version:

Sensor Down:
June 22, 2023 20:16

deployment_id: duly_pro_vervet

Fixes/Action:
Sensor went down on 06/22, in the past has gone down because it's antenna was smashed 

![russell rssi 1 ](https://github.com/floodnet-nyc/flood-sensor/assets/122378043/7133fecd-bc81-4a07-935c-6f04a79cf48f)

![russell 1 rca](https://github.com/floodnet-nyc/flood-sensor/assets/122378043/3f79a531-9a14-4cff-8906-e9b9591c7e0b)

![russell 1 bv](https://github.com/floodnet-nyc/flood-sensor/assets/122378043/2da40faa-5933-48b0-8d6b-754002b287af)

**Comment by Praneethsvch** [comment]
Issues:
1. Keeps switching back to config mode 
2. When is sensing mode - 9999

**Comment by ak6492** [comment]
updated to firmware with no config mode 02/15
