### ISSUE TITLE
RCA - BK: Wallabout/ Throop Ave

### ISSUE THREAD

**Issue by ak6492** [floodnet-nyc/flood-sensor#80]
Sensor Deployed:
March 9, 2023 by FloodNet

Sensor Version: 2.5.

Firmware Version:

deployment_id: mean_flying_fish

Sensor has been very noisy since deployment. Upon inspecting the sensor on 08/31 it was seen that the sensor was very crooked and not leveled at all on the drive rail. The antenna was also damaged, and looked barely operational. The sensor was remounted to be more leveled on 08/31. Need to see if this will fix the noise issue for this particular sensor 

<img width="1343" alt="Screenshot 2023-09-01 at 3 31 31 PM" src="https://github.com/floodnet-nyc/flood-sensor/assets/122378043/68671382-aa57-4dcf-a73b-f9407a3776a4">

![20230831_153731](https://github.com/floodnet-nyc/flood-sensor/assets/122378043/770fd05f-43fd-43a6-85da-8222aad58f21)
![20230831_153722 (1)](https://github.com/floodnet-nyc/flood-sensor/assets/122378043/79922eba-6373-4997-8636-2479b8b2269a)
![20230831_154106 (1)](https://github.com/floodnet-nyc/flood-sensor/assets/122378043/a704c721-9d07-4e33-9db8-84cb118ccdea)

**Comment by cmydlarz** [comment]
Sensor is being observed before we close the issue. New label assigned for possible fix

**Comment by ak6492** [comment]
Observed on 09/08, seems to no longer be getting no returns but may still be noisy

**Comment by ak6492** [comment]
Observed on grafana on 09/15, seems to be doing a lot better. At most one no return value a day. Closing issue for now
